### PR TITLE
MANIFEST.in: Add tests to sdist

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by boxed** [comment]
If you want to run the tests, clone the repo. I don't see the point of this.

**Comment by jayvdb** [comment]
I can't do that in an offline VM used to build RPMs.  So currently we need to create tarballs of your tests each time you do a release, so that we can verify that the software works in combination with all the other versions we have.
https://build.opensuse.org/package/show/devel:languages:python/python-hammett

The latest release is currently failing
https://build.opensuse.org/package/show/home:jayvdb:branches:devel:languages:python/python-hammett

Why distribute an sdist without tests?  You have a universal wheel, which has the package code.  If that is all you care about distributing, an sdist is useless.

**Comment by boxed** [comment]
Ok, that might be a good point. I could just stop supplying an sdist.

I don't understand why you are even running my tests. I'm just a minor experimental test runner...

**Comment by jayvdb** [comment]
It is supported by mutmut , which is also an openSUSE package https://build.opensuse.org/package/show/devel:languages:python/python-mutmut .  hammett is apparently almost 5x faster than pytest, so that would be a good reason why people might want to use it ;-)  That includes me, which is why I package it.

**Comment by boxed** [comment]
Looks like mutmut shipping the tests is just a mistake on my part. 

I honestly don't see the point of this. Why would you even suspect the tests would be different on Ubuntu vs suse? And why aren't you using the python packaging for a python tool?

**Comment by jayvdb** [comment]
It has nothing to do with Ubuntu vs openSUSE.

All distros run tests of all of their Python packages, unless there is some tricky stuff in the package which makes testing it difficult.  This is necessary because they must choose one version of each piece of software, and software often isnt compatible with versions it wasnt tested against.  e.g. distros have been testing all of their Python packages against Python 3.9.  And they raise bugs early, help fix them, etc, etc.  CI for projects only chooses a set of versions valid at the time of a CI build.

As for why, Python packaging doesnt provide build bots like most other languages have, so distro packaging is the only way to ensure that versions undergo acceptance testing before they are pushed down update channels.  Distros also have far more advanced tools for packaging, such as detecting when license files are missing, or when stated licenses are changed, which triggers verification that the license change was done with consent of all contributors.  You'd be surprised with how often Python packages dont fulfill licensing obligations.  e.g. https://git.niklasrosenstein.com/NiklasRosenstein/nr/issues/13 is about a mono repo of many packages with patchy inclusion of license files in the distributions.

Also distros lead the way in what are called reproducible builds, ensuring that the same version rebuilds to produce identical outputs.  setuptools has long been fixed to provide reproducible builds, but pip/wheel/etc have not until recently.  We've fixed most of the bugs in pip/wheel/etc, but there are still some gnarly cases which break this expectation.
https://reproducible-builds.org/
https://wiki.debian.org/ReproducibleBuilds
https://en.opensuse.org/openSUSE:Reproducible_Builds

e.g. here are the core set of Python packages for debian, with most of the packages having tests running.

https://tests.reproducible-builds.org/debian/unstable/amd64/pkg_set_maint_debian-python.html

You can browse Python package build scripts for many distros using repology, e.g. Fedora: https://repology.org/projects/?search=python&inrepo=fedora_rawhide [atomicwrites](https://src.fedoraproject.org/rpms/python-atomicwrites/tree/master)

I'm not doing anything unusual.  myself and openSUSE are merely the first to package any of your Python packages, just like it is first to package @TriOptima packages .  You're lack of familiarity/respect/interest/whatever with distro packaging isnt unusual either.  I have this type of discussion about once a month with a different software developer.  Usually I am successful, but occasionally not.  If I am not successful, it means that we need to do more work to maintain those distro packages.  What never happens is that we're convinced that we should discontinue doing distro packaging and that pip-only packaging is superior.  The end-game is usually that some other person separately attempts to set up the package for their distro, raise the same PRs and issues, and the package developers eventually accept that there is a need for it, even if they dont encounter these use cases themselves.

**Pull request closed without merging**
